site_name: Maoto Agent Docs
site_url: https://package.maoto.world/

nav:
  - Home: index.md
  - Installation: installation.md
  - Package Versions:
      - Stable: stable/api.md
      - Beta: beta/api.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            docstring_style: "numpy"
            members: true  # Include only public methods
            filters: ["!^_"]  # Hides private methods (starting with "_")
<<<<<<< HEAD
=======
            inherited_members: true  # Include inherited methods
            merge_init_into_class: true  # Show __init__ details in class doc
>>>>>>> package-docs
  - macros

extra:
  version:
    stable: "latest"
    beta: "dev"
<<<<<<< HEAD
=======
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/automaoto
    - icon: fontawesome/brands/github
      link: https://github.com/automaoto
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/automaoto
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@automaoto
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/automaoto
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/automaoto/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/automaoto

not_in_nav: |


# Page tree
nav:
  - Home: index.md
  - Package Versions:
      - Stable: stable/api.md
      - Beta: beta/api.md
>>>>>>> package-docs
