site_name: Maoto Package Docs
site_url: https://package.maoto.world/

theme:
  name: material
  favicon: https://maoto.world/favicon.ico
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: dark-blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

  features:
    - content.code.annotate
    - content.code.copy
    - navigation.instant
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            docstring_style: "numpy"
            members: true  # Include only public methods
            filters: ["!^_"]  # Hides private methods (starting with "_")
            inherited_members: true  # Include inherited methods
            merge_init_into_class: true  # Show __init__ details in class doc
  - macros

extra:
  version:
    stable: "latest"
    beta: "dev"
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/automaoto
    - icon: fontawesome/brands/github
      link: https://github.com/automaoto
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/automaoto
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@automaoto
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/automaoto
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/automaoto/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/automaoto

not_in_nav: |


# Page tree
nav:
  - Stable: index.md
  - Beta: beta.md